name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Use Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch modules
      run: go mod download
    - name: Build
      run: make build
    - name: Test
      run: make test
